name: Performance Tests

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  performance-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run Smoke Test
        run: npm run smoke
        
      - name: Run Load Test
        run: npm run load
        
      - name: Run Stress Test
        run: npm run stress
        
      - name: Run Spike Test
        run: npm run spike
        
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: performance-test-reports
          path: reports/
          retention-days: 5
          
      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Performance Test Failure - ${context.workflow}`,
              body: `Performance tests failed in workflow ${context.workflow}\n\nCommit: ${context.sha}\n\nPlease check the test reports for details.`
            }); 